### ISSUE TITLE
Problem running on android

### ISSUE THREAD

**Issue by Angelk90** [mrousavy/StorageBenchmark#2]
Hi @mrousavy , I tried to run the app on a physical android device but I am failing to compile, I get the following errors:

```
yarn run v1.22.4
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 973 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-mmkv
MMKV: node_modules/ found at: /Users/Username/Desktop/StorageBenchmark/app/node_modules
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.

> Configure project :react-native-quick-sqlite
react-native-quick-sqlite: node_modules/ found at: /Users/Username/Desktop/StorageBenchmark/app/node_modules

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':@nozbe_watermelondb' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':@nozbe_watermelondb' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/Username/Desktop/StorageBenchmark/app/node_modules/execa/index.js:174:9)
    at /Users/Username/Desktop/StorageBenchmark/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/Username/Desktop/StorageBenchmark/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/Username/Desktop/StorageBenchmark/app/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I did the linking of the modules on android, but I can't solve the problem.

Have you had similar problems too?

<img width="985" alt="Schermata 2022-05-23 alle 14 22 02" src="https://user-images.githubusercontent.com/20476002/169818423-b0b45ac0-8b98-4c4b-a3e2-80ad6532f697.png">
<img width="979" alt="Schermata 2022-05-23 alle 14 22 11" src="https://user-images.githubusercontent.com/20476002/169818441-05cc5678-f964-4578-9eaf-c622880c9fd5.png">
<img width="982" alt="Schermata 2022-05-23 alle 14 22 20" src="https://user-images.githubusercontent.com/20476002/169818448-6b36c7a6-fbe9-4c73-9212-e0f55563c8f4.png">
<img width="1183" alt="Schermata 2022-05-23 alle 14 22 59" src="https://user-images.githubusercontent.com/20476002/169818460-ce03ecab-2d63-4be5-a6bb-22d9bc259b42.png">

**Comment by drplauska** [comment]
@Angelk90 please try with latest files (https://github.com/mrousavy/StorageBenchmark/pull/1), it worked fine for me on physical android.

**Comment by Angelk90** [comment]
@drplauska : Now it seems to work, the problem do you think was that the variable `kotlinVersion = '1.3.50'` was missing?

**Comment by Angelk90** [comment]
@drplauska : I tried to put it on, but it didn't work.

Anyway the android dependency part is missing, do you think you could do a pr to add them?

I am referring to the screenshots I have put.
